language: csharp

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

mono: none
dotnet: 1.0.0-preview2-003121

matrix:
  global:
    - DOTNETCORE=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
  include:
    - os: linux
      dist: trusty # Ubuntu 14.04
      sudo: required
      env: CONFIGURATION=Debug 
    - os: linux
      dist: trusty
      sudo: required
      env: CONFIGURATION=Release
    - os: osx
      osx_image: xcode7.2 # macOS 10.11
      env: CONFIGURATION=Debug
    - os: osx
      osx_image: xcode7.2
      env: CONFIGURATION=Release

install:
  # Restore dependencies
  - dotnet restore

  # Build projects
  - dotnet build -c $CONFIGURATION -f netcoreapp1.0 ./test/dotnet-test-nunit.test.runner

script:
  # Run tests
  - dotnet run -c $CONFIGURATION -f netcoreapp1.0 -p ./test/dotnet-test-nunit.test.runner
