language: csharp

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

sudo: required
os:
#  - linux
  - osx
dist: trusty # Ubuntu 14.04

mono: none
dotnet: 1.0.0-preview2-003121
env:
  global:
    - DOTNETCORE=1
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
  matrix:
    - CONFIGURATION=Debug
#    - CONFIGURATION=Release

install:
  # Workaround dotnet/cli#3636
  - if test "$TRAVIS_OS_NAME" == "linux"; then
      sudo mkdir -p /usr/lib/mono/xbuild-frameworks/.NETFramework/v4.5.1;
    fi

  - if test "$TRAVIS_OS_NAME" == "osx"; then
      export DOTNET_REFERENCE_ASSEMBLIES_PATH=/Library/Frameworks/Mono.framework/Versions/Current/lib/mono/xbuild-frameworks/;
  #    export DOTNET_REFERENCE_ASSEMBLIES_PATH=/tmp/reference_assemblies
      sudo mkdir -p $DOTNET_REFERENCE_ASSEMBLIES_PATH/.NETFramework/{v.4.5.1}
    fi

  # Restore dependencies
  - dotnet restore

  # Build projects
  - dotnet build -c $CONFIGURATION -f netcoreapp1.0 ./test/dotnet-test-nunit.test.runner

script:
  # Run tests
  - dotnet run -c $CONFIGURATION -f netcoreapp1.0 -p ./test/dotnet-test-nunit.test.runner
